name: "Build and Deploy - Self Hosted"

on:
  workflow_dispatch:
    branches:
      - test_branch

env:
  WORKING_DIRECTORY: 'IISAutoDeploy'
  DOTNET_VERSION: '5.0.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet build --configuration Release --no-restore 

      - name: Publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet publish --configuration Release --output 'dotnetcorewebapp'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: application
          path: '${{ env.WORKING_DIRECTORY }}/dotnetcorewebapp'

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Take application offline
      run: New-Item -Type File -Name app_offline.htm -Path C:\HostingSpaces\admin\AutoDeployTest -Force

    - name: Set application offline
      run: Set-Content C:\HostingSpaces\admin\AutoDeployTest\app_offline.htm 'Under Construction'

    - name: Download new binaries over the top of the app
      uses: actions/download-artifact@v2
      with:
        name: application
        path: C:\HostingSpaces\admin\AutoDeployTest

    - name: Bring the app back online
      run: Remove-Item C:\HostingSpaces\admin\AutoDeployTest\app_offline.htm
